### ISSUE TITLE
Failure on start regarding MVVM

### ISSUE THREAD

**Issue by ScrambledBrain** [SamMackrill/gw2-alternator#30] opened 2022-03-04 19:47 UTC
Hi,
I have a failure on start regarding MVVM.

![2022-03-04 20_42_59 - Window](https://user-images.githubusercontent.com/76404178/156831440-54d45cd9-fb87-47e7-a33e-fc71415dc984.png)

I already have installed:
- .NET 6.0.2
- MVVM Dialogs package from NuGet Gallery

What is missing at this point?
I didn't found a hint on your site.

**Comment by SamMackrill** [comment] 2022-03-06 21:49
Strange, I will take a look

**Comment by SamMackrill** [comment] 2022-03-07 13:35
![image](https://user-images.githubusercontent.com/84898/157044281-1569b4f4-580c-4a19-8322-f6a0488bfc73.png)
Reproduced, this is due to something missing in \AppData\Roaming
Investigating

**Comment by SamMackrill** [comment] 2022-03-07 16:08
Should be fixed in V1.0.5

**Closed by SamMackrill** 2022-03-07 16:08 UTC
Labels: bug
